version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible options
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
